linters:
  enable:
    - bodyclose
    #- depguard
    - dogsled
    - dupl
    - errcheck
    - errorlint
    - exportloopref
    - funlen
    - gocheckcompilerdirectives
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - godox
    - gofmt
    #- goimports
    #- gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    #- lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - revive
    #- staticcheck
    - stylecheck
    - testifylint
    - unconvert
    - unparam
    - unused
    - whitespace
  fast: true