apiVersion: v1
kind: Service
metadata:
  name: org0-ca
spec:
  type: LoadBalancer
  selector:
    app: org0-ca
  ports:
  - port: 7053
    targetPort: 7053
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: org0-ca
spec:
  replicas: 1
  selector:
    matchLabels:
      app: org0-ca
  template:
    metadata:
      labels:
        app: org0-ca
    spec:
      containers:
      - name: org0-ca
        image: hyperledger/fabric-ca:1.5
        ports:
        - containerPort: 7053
        volumeMounts:
        - mountPath: /tmp/hyperledger/fabric-ca
          name: org0-ca-volume
        env:
        - name: FABRIC_CA_SERVER_HOME
          value: "/tmp/hyperledger/fabric-ca/crypto"
        - name: FABRIC_CA_SERVER_TLS_ENABLED
          value: "true"
        - name: FABRIC_CA_SERVER_CSR_CN
          value: "org0-ca"
        # CSR hosts are not required since org0-ca will not generate its TLS sign certificates
        #- name: FABRIC_CA_SERVER_CSR_HOSTS
        #  value: "0.0.0.0,master,org0-*"
        - name: FABRIC_CA_SERVER_DEBUG
          value: "true"
        - name: FABRIC_CA_SERVER_TLS_CERTFILE
          value: "/tmp/hyperledger/fabric-ca/tls/signcerts/cert.pem"
        - name: FABRIC_CA_SERVER_TLS_KEYFILE
          value: "/tmp/hyperledger/fabric-ca/tls/keystore/key.pem"
        command: ["sh"]
        args: ["-c", "fabric-ca-server start -d -b admin-org0:adminpw --port 7053"]
      volumes:
        - name: org0-ca-volume
          hostPath:
            path: /root/hfb/org0/ca/server
            type: Directory
