apiVersion: v1
kind: Service
metadata:
  name: <org-name>-explorer-db
spec:
  type: LoadBalancer
  selector:
    app: <org-name>-explorer-db
  ports:
    - name: explorer-db-port
      port: <explorer-db-port>
      targetPort: <explorer-db-port>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: <org-name>-explorer-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: <org-name>-explorer-db
  template:
    metadata:
      labels:
        app: <org-name>-explorer-db
    spec:
      hostname: <org-name>-explorer-db-pod
      containers:
        - name: <org-name>-explorer-db
          image: ghcr.io/hyperledger-labs/explorer-db:latest
          ports:
            - containerPort: <explorer-db-port>
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: <org-name>-explorer-db-pg-data
          env:
            - name: DATABASE_DATABASE
              value: "fabricexplorer"
            - name: DATABASE_USERNAME
              value: "hppoc"
            - name: DATABASE_PASSWORD
              value: "password"
      volumes:
        - name: <org-name>-explorer-db-pg-data
          hostPath:
            path: <pg-data-dir>
            type: Directory