name: chaincode-cicd-action
run-name: ${{ github.actor }} triggered the pipeline
on:
  push:
    branches:
      - pipeline
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Golang
        uses: actions/setup-go@v4
        with:
          go-version: '1.19'
      - name: Run Golang-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54
  build:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: log into Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build and push image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}/asset-cc:${{ github.sha }}
          file: ./chaincode/Dockerfile
