name: deploy-ccaas
run-name: ${{ github.actor }} triggered the pipeline
on:
  push:
    branches:
      - pipeline
jobs:
#  lint:
#    uses: ./.github/workflows/golangci-lint.yaml
  build:
#    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Set repository to lowercase
        run: |
          echo "repository_lc=${repo,,}" >> ${GITHUB_ENV}
        env:
          repo: '${{ github.repository }}'
      - name: set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: log into Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: test logs
        run: |
          echo "${{ github.repository_lc }}"
          echo "${{ env.repository_lc }}"
          echo "${{ github.repository }}"
          cat $GITHUB_ENV
          echo $repo
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: build and push image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ghcr.io/${{ env.repository_lc }}/asset-cc:${{ github.sha }}
          file: ./chaincode/Dockerfile
          context: ./chaincode
